server:
  port: 8080

#logging:
#  config: classpath:logback-spring-bak.xml

spring:
  application:
    name: transaction-management
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: UTC
        format_sql: true
    hibernate:
      ddl-auto: create




logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
